name: demo_01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6 # 路由 & 状态管理
  cupertino_icons: ^1.0.2
  disk_space: ^0.2.1
  file_manager: ^1.0.2
  # modal_bottom_sheet: ^2.1.2
  path_provider: ^2.0.14
  percent_indicator: ^4.2.3
  permission_handler: ^10.2.0
  sizer: ^2.0.15
  storage_info: ^0.0.1
  flutter_screenutil: ^5.9.3 # 屏幕适配
  url_launcher: ^6.3.0 # url跳转
  share_plus: ^10.0.2 # 分享
  nil: ^1.1.1 # 占位符
  intl: ^0.19.0 # 国际化
  flutter_smart_dialog: ^4.9.8 # 弹窗
  dynamic_color: any # 动态取色

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
