name: demo_01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6 # 路由 & 状态管理
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.3 # 进度条
  flutter_screenutil: ^5.9.3 # 屏幕适配
  url_launcher: ^6.3.0 # url跳转
  share_plus: ^10.0.2 # 分享
  nil: ^1.1.1 # 占位符
  intl: ^0.19.0 # 国际化
  flutter_smart_dialog: ^4.9.8 # 弹窗
  dynamic_color: any # 动态取色
  # 网络请求
  connectivity_plus: ^6.0.5
  dio: ^5.6.0 # 网络请求
  auto_size_text: ^3.0.0 # 文本自适应
  loading_animation_widget: ^1.2.1 # 加载动画
  cached_network_image: ^3.4.1 # 图片缓存
  gap: ^3.0.1 # 间隔
  animated_rating_stars: ^1.0.1 # 评分星标

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/3d/
